import scrapy


class StartupItem(scrapy.Item):
    startup_name = scrapy.Field()
    company_slug = scrapy.Field()
    profile_url = scrapy.Field()
    source = scrapy.Field()
    source_snapshot = scrapy.Field()
    district = scrapy.Field()
    state = scrapy.Field()
    primary_industry = scrapy.Field()
    sectors = scrapy.Field()
    description = scrapy.Field()
    website = scrapy.Field()
    dpiit_recognised = scrapy.Field()
    cin = scrapy.Field()
    funding_signal = scrapy.Field()
    founders = scrapy.Field()
    public_emails = scrapy.Field()
    public_phones = scrapy.Field()
    linkedin = scrapy.Field()
    instagram = scrapy.Field()
    facebook = scrapy.Field()
    twitter = scrapy.Field()
    source_page = scrapy.Field()
    crawl_status = scrapy.Field()
